["async", "fetchUserData", "function", "apiUrl", "https://jsonplaceholder.typicode.com/users"]
["dataContainer", "getElementById", "api-data"]
["try", "catch", "await", "response.json()"]
["dataContainer.innerHTML"]
["appendChild", "userList", "document.createElement", "ul"]
