["addEventListener", "DOMContentLoaded", "function"]
["document.getElementById", "registration-form"]
["form-feedback"]
["username", "email", "password", "trim"]
["messages", "push", "isValid"]
["feedbackDiv", "display"] / script.js doesn't contain: ["Registration successful"] / script.js doesn't contain: ["feedbackDiv.innerHTML", "messages.join", "br", "feedbackDiv.style.color", "#dc3545"]
["username.length"]
